// Generated by LiveScript 1.5.0
(function(){
  var fp, ref$, login, password, urls, state, auth, maybe_update, slice$ = [].slice;
  fp = require("funphan")(300000);
  fp.debug = false;
  ref$ = fp.args, login = ref$[0], password = ref$[1], urls = slice$.call(ref$, 2);
  console.log("start ... login = " + login + ", password = " + password + ", urls = " + JSON.stringify(urls));
  state = {
    submitted: false,
    urls: urls
  };
  fp.parse = function(data){
    console.log("from eval ... " + data);
    return setTimeout(function(){
      var url;
      if (!state.submitted) {
        fp.page.render("screen.png");
      }
      state.submitted = true;
      if (state.urls.length > 0) {
        url = state.urls.pop();
        console.log("trying update " + url);
        return fp.open(url, maybe_update);
      } else {
        console.log("finish script ...");
        return fp.exit(0, false);
      }
    }, 5000);
  };
  auth = function(login, password){
    document.getElementsByName("loginuser")[0].value = login;
    document.getElementsByName("loginpassword")[0].value = password;
    document.forms[0].submit();
    return "logged in with login " + login + " and password " + password;
  };
  maybe_update = function(){
    var links, update;
    links = document.getElementsByClassName('link');
    update = [].filter.call(links, function(el){
      return el.title === "Обновить тему";
    })[0];
    if (update) {
      update.click();
      return "updated!";
    } else {
      return "update is not avaiable ...";
    }
  };
  fp.open("http://www.musicforums.ru/buysell/login.php?bn=mfor_buysell", auth, login, password);
}).call(this);
